name: Build LaTeX Document
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Install TeX Live and pdfjam
      - name: Install TeX Live and pdfjam
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra texlive-pstricks texlive-xetex texlive-fonts-recommended ghostscript
      # Compile LaTeX document with pdflatex
      - name: Compile LaTeX
        run: |
          export TMPDIR=./tempdir
          mkdir -p $TMPDIR
          xelatex main.tex
      # Combine multiple pages into one A4 using pdfjam
      - name: Arrange PDF pages with pdfjam
        run: |
          pdfjam --nup 2x4 --paper a4paper --noautoscale true --frame true --delta "1cm 0.5cm" main.pdf
      # Upload the final PDF as an artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-pdf
          path: main-pdfjam.pdf
  deploy_pdf:
      needs: [build]
      runs-on: ubuntu-latest
      env:
        DIR: .
        FILE: main-pdfjam
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/download-artifact@v4
          with:
            name: output-pdf
            path: main-pdfjam.pdf
        - name: Move pdf
          run: mkdir -p github_deploy && mv -f ${{ env.FILE }}.pdf github_deploy
        - name: Deploy pdf on orphan branch
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./github_deploy
            publish_branch: build
            force_orphan: true

